Community/Controllers/MeetingInfoController.cs
using Community.Data;
using Community.Data.Tables;
using Community.ModelViews.MeetingViewModels;
using Community.ViewModels.MeetingViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Community
{
    public class MeetingInfoController : Controller
    {
        private readonly MeetingManager _meetingManager;
        private readonly UserManager<User> _userManager;
        private readonly MeetingQuery _meetingQuery;
        private readonly LocationQuery _locationQuery;

        public MeetingInfoController(
            UserManager<User> userManager,
            MeetingManager meetingManager,
            MeetingQuery meetingQuery,
            LocationQuery locationQuery
            )
        {
            _meetingManager = meetingManager;
            _userManager = userManager;
            _meetingQuery = meetingQuery;
            _locationQuery = locationQuery;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userMeetings = await _meetingQuery.GetLastRegisteredMeetingsAsync(10);

            List<MeetingGeneralInfoViewModel> modelList = new List<MeetingGeneralInfoViewModel>();

            foreach (var item in userMeetings)
            {
                modelList.Add(
                    new MeetingGeneralInfoViewModel
                    {
                        Id = item.Id,

                        Name = item.Name,

                        Description = string.Concat(item.Description.Take(15)),

                        CityName = (await _locationQuery.GetCityByIdAsync(item.CitiesId)).Name,

                        CategoryName = (await _meetingQuery.GetMeetingCategoryByIdAsync(item.MeetingCategoryId)).Name,

                        ConfirmedUsersRequests = await _meetingQuery.GetMeetingConfirmedUsersCountAsync(item.Id),

                        PhotoPath = item.PhotoPath,

                        ShortDateString = item.MeetingDate.ToShortDateString()
                    });
            }

            return View(modelList);
        }

        [HttpGet]
        public async Task<IActionResult> MeetingsOwn()
        {
            var userId = _userManager.GetUserId(User);
            var userMeetings = await _meetingQuery.GetUserCreatedMeetingsAsync(userId);


            List<MeetingOwnInfoViewModel> modelList = new List<MeetingOwnInfoViewModel>();

            foreach (var item in userMeetings)
            {
                modelList.Add(
                    new MeetingOwnInfoViewModel
                    {
                        Id = item.Id,

                        Name = item.Name,

                        CategoryName = (await _meetingQuery.GetMeetingCategoryByIdAsync(item.MeetingCategoryId)).Name,

                        CityName = (await _locationQuery.GetCityByIdAsync(item.CitiesId)).Name,

                        ConfirmedUsersRequests = await _meetingQuery.GetMeetingConfirmedUsersCountAsync(item.Id),

                        UnconfirmedUsersRequests = await _meetingQuery.GetMeetingUnconfirmedUsersCountAsync(item.Id),

                        PhotoPath = item.PhotoPath,

                        ShortDateString = item.MeetingDate.ToShortDateString()
                    });
            }

            return View(modelList);
        }

        [HttpGet]
        public async Task<IActionResult> MeetingsSubscribed()
        {
            var userId = _userManager.GetUserId(User);
            var userMeetings = await _meetingQuery.GetUserSubscribedMeetingsAsync(userId);

            List<MeetingGeneralInfoViewModel> modelList = new List<MeetingGeneralInfoViewModel>();

            foreach (var item in userMeetings)
            {
                modelList.Add(
                    new MeetingGeneralInfoViewModel
                    {
                        Id = item.Id,

                        Name = item.Name,

                        CityName = (await _locationQuery.GetCityByIdAsync(item.CitiesId)).Name,

                        CategoryName = (await _meetingQuery.GetMeetingCategoryByIdAsync(item.MeetingCategoryId)).Name,

                        ConfirmedUsersRequests = await _meetingQuery.GetMeetingConfirmedUsersCountAsync(item.Id),

                        PhotoPath = item.PhotoPath,

                        ShortDateString = item.MeetingDate.ToShortDateString()
                    });
            }

            return View(modelList);
        }

        [HttpGet]
        public async Task<IActionResult> MeetingGeneralInfo(int meetingId)
        {
            var meeting = await _meetingQuery.GetMeetingByIdAsync(meetingId);

            var model = new MeetingGeneralInfoViewModel
            {
                Id = meeting.Id,

                Name = meeting.Name,

                Description = meeting.Description,

                CategoryName = (await _meetingQuery.GetMeetingCategoryByIdAsync(meeting.MeetingCategoryId)).Name,

                CityName = (await _locationQuery.GetCityByIdAsync(meeting.CitiesId)).Name,

                ConfirmedUsersRequests = await _meetingQuery.GetMeetingConfirmedUsersCountAsync(meeting.Id),

                PhotoPath = meeting.PhotoPath,

                ShortDateString = meeting.MeetingDate.ToShortDateString()
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> MeetingOwnInfo(int meetingId)
        {
            var userId = _userManager.GetUserId(User);
            var ownership = await _meetingQuery.CheckMeetingOwnerAsync(meetingId, userId);

            if (ownership == false)
            {
                RedirectPermanent(Url.Action("Index", "Home"));
            }

            var meeting = await _meetingQuery.GetMeetingByIdAsync(meetingId);

            var model = new MeetingOwnInfoViewModel
            {

                Id = meeting.Id,

                Name = meeting.Name,

                Description = meeting.Description,

                CategoryName = (await _meetingQuery.GetMeetingCategoryByIdAsync(meeting.MeetingCategoryId)).Name,

                CityName = (await _locationQuery.GetCityByIdAsync(meeting.CitiesId)).Name,

                ConfirmedUsersRequests = await _meetingQuery.GetMeetingConfirmedUsersCountAsync(meeting.Id),

                UnconfirmedUsersRequests = await _meetingQuery.GetMeetingUnconfirmedUsersCountAsync(meeting.Id),

                PhotoPath = meeting.PhotoPath,

                ShortDateString = meeting.MeetingDate.ToShortDateString()
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> MeetingUnconfirmedSubscribers(int meetingId)
        {
            var userId = _userManager.GetUserId(User);

            var checkResult = await _meetingQuery.CheckMeetingOwnerAsync(meetingId, userId);

            if (checkResult == false)
            {
                return RedirectPermanent(Url.Action("Index", "Home"));
            }

            var unconfirmedSubscribers = await _meetingQuery.GetMeetingUnconfirmedUsersAsync(meetingId);

            var subscribersList = new List<MeetingSubscriberViewModel>();

            var meeting = await _meetingQuery.GetMeetingByIdAsync(meetingId);

            foreach (var item in unconfirmedSubscribers)
            {
                subscribersList.Add(
                        new MeetingSubscriberViewModel
                        {
                            UserId = item.Id,
                            UserFirstName = item.UserFirstName ?? item.Email,
                            UserLastName = item.UserLastName,
                            UserPhotoPath = item.PhotoPath ?? " ",

                            MeetingId = meeting.Id,
                            MeetingName = meeting.Name,
                            MeetingPhotoPath = meeting.PhotoPath
                        }
                    );
            }

            return View(subscribersList);
        }

        [HttpGet]
        public async Task<IActionResult> MeetingConfirmedSubscribers(int meetingId)
        {
            var userId = _userManager.GetUserId(User);

            var checkResult = await _meetingQuery.CheckMeetingOwnerAsync(meetingId, userId);

            if (checkResult == false)
            {
                return RedirectPermanent(Url.Action("Index", "Home"));
            }

            var unconfirmedSubscribers = await _meetingQuery.GetMeetingConfirmedUsersAsync(meetingId);

            var subscribersList = new List<MeetingSubscriberViewModel>();

            var meeting = await _meetingQuery.GetMeetingByIdAsync(meetingId);

            foreach (var item in unconfirmedSubscribers)
            {
                subscribersList.Add(
                        new MeetingSubscriberViewModel
                        {
                            UserId = item.Id,
                            UserFirstName = item.UserFirstName,
                            UserLastName = item.UserLastName,
                            UserPhotoPath = item.PhotoPath ?? " ",

                            MeetingId = meeting.Id,
                            MeetingName = meeting.Name,
                            MeetingPhotoPath = meeting.PhotoPath
                        }
                    );
            }

            return View(subscribersList);
        }

    }
}

Community/Controllers/MeetingManageController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Community.ModelViews.MeetingViewModels;
using Community.Data;
using Community.Data.Tables;
using Microsoft.AspNetCore.Identity;
using Community.Services;
using Community.ViewModels.MeetingViewModels;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using System;

namespace Community.Controllers
{
    [Authorize]
    public class MeetingManageController : Controller
    {
        private readonly MeetingManager _meetingManager;
        private readonly UserManager<User> _userManager;
        private readonly MeetingQuery _meetingQuery;
        private readonly LocationQuery _locationQuery;
        private readonly FileService _fileService;

        public MeetingManageController(
            UserManager<User> userManager,
            MeetingManager meetingManager,
            MeetingQuery meetingQuery,
            LocationQuery locationQuery,
            FileService fileService
            )
        {
            _userManager = userManager;
            _meetingManager = meetingManager;
            _meetingQuery = meetingQuery;
            _locationQuery = locationQuery;
            _fileService = fileService;
        }


        [HttpGet]
        public async Task<IActionResult> MeetingCreate()
        {
            MeetingCreateViewModel model = new MeetingCreateViewModel();

            model.MeetingCategories = await _meetingQuery.GetMeetingCategoriesAsync();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> MeetingCreate(MeetingCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.MeetingCategories = await _meetingQuery.GetMeetingCategoriesAsync();
                return View(model);
            }

            if (await _locationQuery.GetCityByIdAsync(model.CityId) == null)
            {
                ModelState.AddModelError("CityId", "Please choose a city");
                model.MeetingCategories = await _meetingQuery.GetMeetingCategoriesAsync();
                return View(model);
            }
            
            
            string photoPath = await _fileService.SaveImage(model.PhotoPath);

            var userId = _userManager.GetUserId(User);

            var meeting = new Meeting
            {
                Name = model.Name,
                Description = model.Description,
                CitiesId = model.CityId ,
                MeetingCategoryId = model.MeetingCategoryId,
                MeetingDate = model.MeetingDate,
                PhotoPath = photoPath,
                UserId = userId,
            };

            var result = await _meetingManager.CreateMeetingAsync(meeting);

            if (result == OperationResult.Failed)
            {
                return View(model);
            }

            return RedirectPermanent(Url.Action("Index", "MeetingInfo"));
        }


        [HttpGet]
        public async Task<IActionResult> MeetingEdit(int meetingId)
        {
            var userId = _userManager.GetUserId(User);
            var checkOwnership = await _meetingQuery.CheckMeetingOwnerAsync(meetingId, userId);

            if (checkOwnership == false)
            {
                return RedirectPermanent(Url.Action("Index", "MeetingInfo"));
            }

            var meeting = await _meetingQuery.GetMeetingByIdAsync(meetingId);

            var meetingCategories = await _meetingQuery
                .GetMeetingCategoriesAsync();

            var model = new MeetingEditViewModel
            {
                Id = meeting.Id,
                Name = meeting.Name,
                Description = meeting.Description,                
                MeetingCategoryId = meeting.MeetingCategoryId,
                MeetingCategories = meetingCategories,
                MeetingDate = meeting.MeetingDate,
                CurrentPhotoPath = meeting.PhotoPath,
                CityId = meeting.CitiesId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> MeetingEdit(MeetingEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            string photoPath = null;
            if (model.PhotoSource != null)
            {
                photoPath = await _fileService
                    .UpdateImageAsync(model.CurrentPhotoPath, model.PhotoSource);
            }

            var userId = _userManager.GetUserId(User);

            var meeting = new Meeting
            {
                Id=model.Id,
                Name = model.Name,
                Description = model.Description,
                MeetingCategoryId = model.MeetingCategoryId,
                MeetingDate = model.MeetingDate,
                PhotoPath = photoPath ?? model.CurrentPhotoPath,
                UserId = userId,
                CitiesId = model.CityId
            };

            var result = await _meetingManager.EditMeetingAsync(meeting);

            if (result == OperationResult.Failed)
            {
                return View(model);
            }

            return RedirectPermanent(Url.Action("MeetingsOwn", "MeetingInfo"));
        }


        public async Task<IActionResult> MeetingDelete(int meetingId)
        {
            var userId = _userManager.GetUserId(User);

            if (await _meetingQuery.CheckMeetingOwnerAsync(meetingId, userId) == false)
            {
                return Content("You are not meeting owner");
            }
            
            var result = await _meetingManager.RemoveMeetingAsync(meetingId);

            if (result == OperationResult.Failed)
            {
                return Content("o_O ... Something happens ...");
            }

            return RedirectPermanent(Url.Action("MeetingsOwn", "MeetingInfo"));
        }

        [HttpPost]
        public async Task<IActionResult> MeetingSubscribe(int meetingId)
        {

            var userId = _userManager.GetUserId(User);

            if (userId == null)
            {
                return RedirectToAction("LogIn", "Account");
            }

            var result = await _meetingManager.SubscribeMeetingAsync(meetingId, userId);

            if (result == OperationResult.Failed)
            {
                return Content("o_O ... Something happens ... MeetingSubscribe");
            }

            return PartialView("~/Views/MeetingPartials/_UserSubscriptionPartial.cshtml", meetingId);
        }

        [HttpPost]
        public async Task<IActionResult> MeetingUnsubscribe(int meetingId)
        {
            var userId = _userManager.GetUserId(User);
            bool subscribed = await _meetingQuery.IsUserSubscribedMeetingAsync(meetingId, userId);

            if (!subscribed)
            {
                return Content("o_O ... Something happens ... MeetingUnsubscribe : User is unsubscribed");
            }

            var result = await _meetingManager.UnsubscribeMeetingAsync(meetingId, userId);

            if (result == OperationResult.Failed)
            {
                return Content("o_O ... Something happens ... MeetingUnsubscribe Unsubscription failed");
            }

            return PartialView("~/Views/MeetingPartials/_UserSubscriptionPartial.cshtml", meetingId);
        }


        [HttpPost]
        public async Task MeetingAcceptUser(string userId, int meetingId)
        {
            var result = await _meetingManager.ApproveMeetingParticipant(meetingId, userId);

            if (result == OperationResult.Failed)
            {
                throw new Exception("Proccess failed");
            }
        }

        [HttpPost]
        public async Task MeetingDeclineUser(string userId, int meetingId)
        {
            var result = await _meetingManager.DeclineMeetingParcipant(meetingId, userId);

            if (result == OperationResult.Failed)
            {
                throw new Exception("Proccess failed");
            }
        }

    }
}

Community/Views/MeetingInfo/Index.cshtml
@model IEnumerable<MeetingGeneralInfoViewModel>
@{
    ViewData["Title"] = "Index";
}

<h3 class="text-info">Last meetings</h3>

<div class="container-fluid">

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-4 col-md-3 col-lg-2">
            <div class="thumbnail">
                <img src="@item.PhotoPath"  style="height : 100px" alt="...">
                <div class="caption">
                   <h3 class="text-center">@item.Name</h3>
                    <h5>@item.CategoryName</h5>
                    <h5>@item.CityName</h5>
                    <h5>Date : @item.ShortDateString</h5>
                    <h5>Members : @item.ConfirmedUsersRequests</h5>
                    <p>@item.Description ...</p>
                    <p><a asp-controller="MeetingInfo" asp-action="MeetingGeneralInfo" asp-route-meetingId="@item.Id" class="btn btn-primary">More details</a></p>
                </div>
            </div>
        </div>
    }
</div>
</div>

Community/Views/MeetingInfo/MeetingConfirmedSubscribers.cshtml
@model IEnumerable<MeetingSubscriberViewModel>


<div class="container-fluid">
    @foreach (var item in Model)
    {
        <div class="meetingBox">
            <div class="row">
                <div class="col-sm-6">
                    <img src="@item.UserPhotoPath" alt="user photo" class="img-rounded img-responsive" />
                    <p>@item.UserFirstName @item.UserLastName</p>
                </div>
                <div class="col-sm-6">
                    <img src="@item.MeetingPhotoPath" alt="meeting photo" class="img-rounded img-responsive" />
                    <p>@item.MeetingName</p>
                </div>
            </div>
            <div class="row">
                <a asp-controller="MeetingManage" asp-action="MeetingDeclineUser"
                   data-userId="@item.UserId" data-meetingId="@item.MeetingId"
                   class="btn btn-success" id="userDeclineBtn">
                    Decline
                </a>
            </div>
        </div>
    }
</div>
<script>
    document.onreadystatechange = function () {
        if (document.readyState == "complete") {

            Main();
        }
    }

    function Main() {

        $('#userDeclineBtn').on('click', function (event) {
            event.preventDefault();
            var userId = $(this).attr('data-userId');
            var meetingId = $(this).attr('data-meetingId');
            let obj = $(this);
            $.ajax(
                {
                    url: 'MeetingDeclineUser?userId=' + userId + '&&meetingId=' + meetingId,
                    method: 'POST'
                })
                .done(function (data) {
                    console.log('before delete' + obj);
                    obj.parents('.meetingBox').remove();
                });
        });

    }

</script>

Community/Views/MeetingInfo/MeetingGeneralInfo.cshtml
@model MeetingGeneralInfoViewModel


<div class="container-fluid">

    <div class="row">
        <div class="col-sm-offset-3 col-sm-6 ">
            <img src="@Model.PhotoPath" class="img-responsive" style="height:200px" alt="event photo" />

            <p>@Model.Name</p>

            <p>Category : @Model.CategoryName</p>

            <p>City : @Model.CityName</p>

            <p>Date : @Model.ShortDateString</p>

            <p>Users already joined : @Model.ConfirmedUsersRequests</p>

            @{
                await Html.RenderPartialAsync("~/Views/MeetingPartials/_UserSubscriptionPartial.cshtml", Model.Id);
            }

            <p>@Model.Description</p>
        </div>
    </div>
</div>

Community/Views/MeetingInfo/MeetingOwnInfo.cshtml
@model MeetingOwnInfoViewModel


<div class="container-fluid">

    <div class="row">
        <div class="col-sm-offset-3 col-sm-6 ">
            <img src="@Model.PhotoPath" class="img-responsive" alt="event photo" />

            <p>@Model.Name</p>

            <p>Category : @Model.CategoryName</p>

            <p>City : @Model.CityName</p>

            <p>Date : @Model.ShortDateString</p>

            <p>Users already joined : @Model.ConfirmedUsersRequests</p>

            <a asp-controller="MeetingInfo" asp-action="MeetingUnconfirmedSubscribers" asp-route-meetingId="@Model.Id" class="btn btn-primary">
                Users want to join <span class="badge">@Model.UnconfirmedUsersRequests</span>
            </a>

            <a asp-controller="MeetingManage" asp-action="MeetingEdit" asp-route-meetingId="@Model.Id" class="btn btn-primary">Edit</a>
            <a asp-controller="MeetingManage" asp-action="MeetingDelete" asp-route-meetingId="@Model.Id" class="btn btn-danger">Delete</a>

            <p>@Model.Description</p>
        </div>
    </div>

</div>

Community/Views/MeetingInfo/MeetingUnconfirmedSubscribers.cshtml
@model IEnumerable<MeetingSubscriberViewModel>


<div class="container-fluid">
    @foreach (var item in Model)
    {
        <div class="meetingBox">
            <div class="row">
                <div class="col-sm-6">
                    <img src="@item.UserPhotoPath" alt="user photo" class="img-rounded img-responsive" />
                    <p>@item.UserFirstName @item.UserLastName</p>
                </div>
                <div class="col-sm-6">
                    <img src="@item.MeetingPhotoPath" alt="meeting photo" class="img-rounded img-responsive" />
                    <p>@item.MeetingName</p>
                </div>
            </div>
            <div class="row">
                <a asp-controller="MeetingManage" asp-action="MeetingAcceptUser"
                   
                   data-userId="@item.UserId" data-meetingId="@item.MeetingId"
                   class="btn btn-success" id="userAcceptBtn">
                    Accept
                </a>
                <a asp-controller="MeetingManage" asp-action="MeetingDeclineUser"
                   
                   data-userId="@item.UserId" data-meetingId="@item.MeetingId"
                   class="btn btn-success" id="userDeclineBtn">
                    Decline
                </a>
            </div>
        </div>

    }
</div>
<script>
    document.onreadystatechange = function () {
        if (document.readyState == "complete") {
           
            Main();
        }
    }

    function Main() {

        $('#userAcceptBtn').on('click', function (event) {
            event.preventDefault();
            var userId = $(this).attr('data-userId');
            var meetingId = $(this).attr('data-meetingId');
            let obj = $(this);
            $.ajax({
                url: 'MeetingAcceptUser?userId=' + userId + '&&meetingId=' + meetingId,
                method: 'POST'
            }).done(function (data) {
                obj.parents('.meetingBox').remove();
            });
        });

        $('#userDeclineBtn').on('click', function (event) {
            event.preventDefault();
            var userId = $(this).attr('data-userId');
            var meetingId = $(this).attr('data-meetingId');
            let obj = $(this);
            $.ajax(
                {
                    url: 'MeetingDeclineUser?userId=' + userId + '&&meetingId=' + meetingId,
                    method: 'POST'
                })
                .done(function (data) {
                    console.log('before delete' + obj);
                    obj.parents('.meetingBox').remove();
            });
        });

    }

</script>

Community/Views/MeetingInfo/MeetingsOwn.cshtml
@model IEnumerable<MeetingOwnInfoViewModel>

    <a asp-controller="MeetingManage" asp-action="MeetingCreate" class="btn btn-success">Create new event</a>

<div class="container-fluid">

    @foreach (var item in Model)
    {

        <div class="row">
            <div class="col-sm-10 col-md-10">
                <div class="thumbnail">
                    <div class="row">
                        <div class="col-sm-4">
                            <img src="@item.PhotoPath" alt="..." width="150" height="100">
                        </div>
                        <div class="col-sm-8">
                            <div class="caption">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p>@item.Name</p>
                                        <p>Category : @item.CategoryName</p>
                                        <p>Date : @item.ShortDateString</p>
                                        <p>City : @item.CityName</p>
                                    </div>
                                    <div class="col-sm-6">

                                        <a asp-controller="MeetingInfo" asp-action="MeetingConfirmedSubscribers" asp-route-meetingId="@item.Id">Accepted users : @item.ConfirmedUsersRequests</a>

                                        <a asp-controller="MeetingInfo" asp-action="MeetingUnconfirmedSubscribers" asp-route-meetingId="@item.Id" class="btn btn-primary">
                                            Users want to join <span class="badge">@item.UnconfirmedUsersRequests</span>
                                        </a>


                                        <div class="dropdown">
                                            <br />
                                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                more actions
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                                <li><a asp-controller="MeetingInfo" asp-action="MeetingOwnInfo" asp-route-meetingId="@item.Id">Info</a></li>
                                                <li><a asp-controller="MeetingManage" asp-action="MeetingEdit" asp-route-meetingId="@item.Id">Edit</a></li>
                                                <li><a asp-controller="MeetingManage" asp-action="MeetingDelete" asp-route-meetingId="@item.Id">Delete</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Community/Views/MeetingInfo/MeetingsSubscribed.cshtml
@model IEnumerable<MeetingGeneralInfoViewModel>


<div class="container-fluid">

    @foreach (var item in Model)
    {
        <div class="row">
            <div class="col-sm-10 col-md-10">
                <div class="thumbnail">
                    <div class="row">
                        <div class="col-sm-4">
                            <img src="@item.PhotoPath" alt="..." width="150" height="100">
                        </div>
                        <div class="col-sm-8">
                            <div class="caption">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p>@item.Name</p>
                                        <p>Category : @item.CategoryName</p>
                                        <p>Date : @item.ShortDateString</p>
                                        <p>City : @item.CityName</p>
                                    </div>
                                    <div class="col-sm-6">

                                        <p>Accepted users : @item.ConfirmedUsersRequests</p>

                                        <div class="dropdown">

                                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                more actions
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                                <li><a asp-controller="MeetingInfo" asp-action="GeneralMeetingInfo" asp-route-meetingId="@item.Id">Info</a></li>
                                                <li>
                                                    @{
                                                        await Html.RenderPartialAsync("~/Views/MeetingPartials/_UserSubscriptionPartial.cshtml", item.Id);
                                                    }
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>