Community/Controllers/LocationController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Community.Data;

namespace Community.Controllers
{
    public class LocationController : Controller
    {
        private readonly LocationQuery _locationQuery;

        public LocationController(LocationQuery locationQuery)
        {
            _locationQuery = locationQuery;
        }

        [HttpGet]
        public JsonResult Autocomplete(string term)
        {
            var model = _locationQuery
                .GetCityStartsWith(term,10);

            return model;
        }
    }
}

Community/Views/MeetingPartials/_LocationSearchPartial.cshtml
@model IMeetingModifiable

<div>
    <label asp-for="CityId" class="control-label"></label>
    <input id="City" type="search" value="" name="searchTerm" data-otf-autocomplete="@Url.Action("Autocomplete","Location")" />
    <input asp-for="CityId" style="display:none" />
    <span asp-validation-for="CityId" class="text-danger"></span>
</div>

<script>

    document.onreadystatechange = function () {
        if (document.readyState == "complete") {

            Main();
        }
    }

    function Main() {

        $(function () {

            var createAutocomplete = function () {
                var $input = $(this);

                var options = {
                    source: $input.attr("data-otf-autocomplete")
                };

                $("#City").autocomplete({
                    select: function (event, ui) {
                        $('#CityId').val(ui.item.cityId);
                    }
                });

                $input.autocomplete(options);
            }

            $("input[data-otf-autocomplete]").each(createAutocomplete);

        });
    }

</script>

Community/Views/MeetingPartials/_UserSubscriptionPartial.cshtml
@inject MeetingQuery _meetingQuery
@inject UserManager<User> _userManager
@model int

@{
    var userId = _userManager.GetUserId(User);
}


<div class="subscriptionArea">
    @{
        // If user not loged in
        if (userId == null)
        {
            <a asp-controller="Account" asp-action="LogIn" class="btn btn-primary">Log in to subscribe</a>
        }
        // If user is not subscribed
        else if (userId != null && !await _meetingQuery.IsUserSubscribedMeetingAsync(Model, userId))
        {
            <a class="subscribeBtn btn btn-success" data-meetingId="@Model">Subscribe</a>
        }
        // If user is subscribed
        else if (userId != null && await _meetingQuery.IsUserSubscribedMeetingAsync(Model, userId))
        {
            <a class="unsubscribeBtn btn btn-danger" data-meetingId="@Model">Unsubscribe</a>
        }
    }
</div>
<script>

    document.onreadystatechange = function () {
        if (document.readyState == "complete") {

            Main();
        }
    }

    function Main() {
        $(document).ready(function () {

            SubscribeBtnsForEvent();

            function SubscribeBtnsForEvent() {

                var subscribeBtn = $('.subscribeBtn');
                var unsubscribeBtn = $('.unsubscribeBtn');
                var subscriptionArea = $('.subscriptionArea');

                if (subscribeBtn) {
                    $(subscribeBtn).on('click', function (event) {
                        event.preventDefault();
                        event.stopPropagation();
                        var meetingId = $(this).attr('data-meetingId');
                        let obj = $(this);

                        $.ajax(
                            {
                                url: '/MeetingManage/MeetingSubscribe?meetingId=' + meetingId,
                                type: 'POST'
                            })
                            .fail(function () {
                                url: 'Error'
                            })
                            .done(function (data) {
                                obj.parent().html(data);
                                SubscribeBtnsForEvent();
                            });
                    });
                }

                if (unsubscribeBtn) {
                    $(unsubscribeBtn).on('click', function (event) {
                        event.preventDefault();
                        event.stopPropagation();
                        var meetingId = $(this).attr('data-meetingId');
                        let obj = $(this);

                        $.ajax(
                            {
                                url: '/MeetingManage/MeetingUnsubscribe?meetingId=' + meetingId,
                                type: 'POST'
                            })
                            .fail(function () {
                                url: 'Error'
                            })
                            .done(function (data) {
                                obj.parent().html(data);
                                SubscribeBtnsForEvent();
                            });

                    });
                }
            }

        });
    }
</script>